### ISSUE TITLE
Big World Setup: Required for EET compatibility?

### ISSUE THREAD

**Issue by GregCampbellPresents** [Skitia/Emily-BG1#1]
Greetings!

According to the below EET compatibility list, some of your mods (Emily, Vienxay, Kale) say they must be patched by the Big World Setup program to work.  How true is that nowadays?

http://eetcompatiblemods.baldursextendedworld.com

If this is no longer true, contact the list maintainer and have that part removed from the list.

http://baldursextendedworld.com/Vanilla_Forums/discussion/19/proposed-mod-to-add

Thankee!

**Comment by Skitia** [comment]
There's one minor fix I want to do in regards to EET dialogues with other NPCs, then I will try and remind the site owner to update it again.
